[package]
name = "squaredb"
version = "1.0.0-beta5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.6"
toml = "0.8.8"
parking_lot = "0.11.0"
chrono = "0.4"
base64 = "0.12"
hex = "0.4"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["macros"] }
lazy_static = "1.4.0"
