[server]
host = "127.0.0.1"
port = "9000"
endpoint = "db"
allowedIps = "*"

[auth]
username = "admin"
password = "admin"
role = "admin"
shareKeyRead = ""
shareKeyWrite = ""
shareKeyReadAndWrite = ""

[engine]
mode = "dev"
enableDeleteTable = "true"
enableDeleteRow = "true"
enableForceCreation = "true"
enableCache = "true"
enableTableHashing = "true"

[packages]
packages = [
"selec999t"
]